[versions]
gradle-node = "7.1.0"
kotest = "6.1.1"
kotlin = "2.3.0"
mockk = "1.14.7"
spotless = "8.2.0"
spring-boot = "4.0.2"
spring-dependency-management = "1.1.7"
version-catalog-update = "1.0.1"

[libraries]
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core" }
kotest-bom = { module = "io.kotest:kotest-bom", version.ref = "kotest" }
kotest-extensions-spring = { module = "io.kotest:kotest-extensions-spring" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
reactor-kotlin-extensions = { module = "io.projectreactor.kotlin:reactor-kotlin-extensions" }
reactor-test = { module = "io.projectreactor:reactor-test" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }

[plugins]
gradle-node = { id = "com.github.node-gradle.node", version.ref = "gradle-node" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
